# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM ghcr.io/astral-sh/uv:alpine

# Set the working directory
WORKDIR /app

# Copy all files
COPY . .

# Install system dependencies: python3, pip and build tools
RUN apk add --no-cache python3 py3-pip build-base

# Upgrade pip (with --break-system-packages to override external management) and install project dependencies
RUN pip3 install --upgrade pip --break-system-packages \
    && pip3 install . --no-cache-dir --break-system-packages

# Synchronize uv dependencies if needed
RUN uv sync

# Command to run the MCP server using uv
CMD ["uv", "run", "mcp-sbom"]
